#!/bin/sh

# This script cals between the flatac plugin
# and the verifications tool, namely eldarica and flatac
# 
# You need to set the variables :

# flatac_install_path : Path to flatac plugin sources 
# nts_bin_path : Root path for java nts binary distribution
# nts_jar, antlr_jar and flata_jar might be updated in futures
# java nts_lib releases.
# You may consider adding the current path to your PATH global
# environement variable.
#  




flatac_install_path=/home/fgarnier/REPOSITORIES/flatac
nts_bin_path=/Users/florent/bin/flata_pack/NTS_BIN/release-13-01-07/
nts_jar=${nts_bin_path}/nts.jar
antlr_jar=${nts_bin_path}/antlr-3.3-complete.jar
flata_jar=${nts_bin_path}/flata.jar
flatac_basic_nts_lib="${flatac_install_path}/base_nts_libraries/base_fun.ca_lib"

if [ $# = 0 ]
 then
  echo $0 "program_name.nts"
  exit 1
 else

csourcefile=$1
cafilename=$1

echo "[FLATA :] Analysis of ${1}"
java -cp ${nts_jar}:${antlr_jar} client.PrintVisitor $cafilename && java -cp ${flata_jar}:${nts_jar}:${antlr_jar} verimag.flata.Main -t-merge-prec -t-fullincl -ce-less ${cafilename}


fi

