.PHONY: clean all
all:
	@cd ssl/ && make -f makefile.sub && cd 
	@cd c_upon_sslandnts_sem/ && make -f makefile.sub && cd 
	@cd global_mem/ && make -f makefile.sub && cd 
	@cd ./ && make -f makefile.sub && cd 
clean:
	@cd ssl/ && make -f makefile.sub clean && cd 
	@cd c_upon_sslandnts_sem/ && make -f makefile.sub clean && cd 
	@cd global_mem/ && make -f makefile.sub clean && cd 
	@cd ./ && make -f makefile.sub clean && cd 
